version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      rabbitmq:
        condition: service_healthy

  contactform:
    build: contactform
    volumes:
      - ./contactform:/usr/share/nginx/html
    ports:
      - 8080:8080
